### ISSUE TITLE
Fix the alignment when for Arabic version

### ISSUE THREAD

**Issue by Jamil-Bailony** [ReCoded-Org/capstone-istanbul-safe_place#157]
- [x] change the navbar `margin-left:auto` to flex space between and fix element width

- [x] fix the footer alignment (flex space between)

- [x] center the description in about page

- [x]  check page consistency when Arabic is chosen

![image](https://user-images.githubusercontent.com/30551053/99887364-bfb33580-2c54-11eb-98fb-b7c5407ed38c.png)

![image](https://user-images.githubusercontent.com/30551053/99887368-c80b7080-2c54-11eb-86eb-affd8ae8bee0.png)

**Comment by hiba-machfej** [comment]
Jamil it looks like this on my screen
![Screen Shot 2020-11-22 at 2 54 53 PM](https://user-images.githubusercontent.com/58190902/99903025-b23c9080-2cd2-11eb-9a8e-e3add1d0adcb.png)
